import { EmployeePerformanceComponent } from "@/components/dashboard/employee-performance";
import { Employee } from "@/app/interfaces/interfaces";

async function getEmployeeData(id: string): Promise<Employee> {
    // This is a mock function. In a real application, you would fetch data from an API or database
    const employees: Employee[] = [
        { id: "1", name: "Sergio H.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar1.png", email: "sergio.h@cardealership.com", phone: "+1 (555) 111-2222", location: "New York, NY", totalInteractions: 120, resolutionRate: 88, conversionRate: 12, averageSentiment: 0.75, specializations: ["SUVs", "Hybrid Cars", "Trade-ins"], topAchievements: ["Top salesperson Q1 2023", "Customer service excellence award", "Highest test drive conversion rate"] },
        { id: "2", name: "Andrea R.", position: "Customer Service", avatar: "/dashboard/avatars/avatar2.png", email: "andrea.r@cardealership.com", phone: "+1 (555) 222-3333", location: "Chicago, IL", totalInteractions: 180, resolutionRate: 95, conversionRate: 10, averageSentiment: 0.85, specializations: ["Customer Retention", "Complaint Resolution", "Product Knowledge"], topAchievements: ["Highest customer satisfaction score", "Reduced average resolution time by 20%", "Implemented new customer feedback system"] },
        { id: "3", name: "John D.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar3.png", email: "john.d@cardealership.com", phone: "+1 (555) 333-4444", location: "Los Angeles, CA", totalInteractions: 140, resolutionRate: 90, conversionRate: 14, averageSentiment: 0.78, specializations: ["Luxury Vehicles", "Financing", "Leasing"], topAchievements: ["Top salesperson Q3 2023", "Highest upsell rate", "Successfully launched VIP customer program"] },
        { id: "4", name: "Jane S.", position: "Customer Service", avatar: "/dashboard/avatars/avatar4.png", email: "jane.s@cardealership.com", phone: "+1 (555) 444-5555", location: "Houston, TX", totalInteractions: 160, resolutionRate: 93, conversionRate: 11, averageSentiment: 0.82, specializations: ["Technical Support", "Online Chat Support", "Customer Education"], topAchievements: ["Developed new online support system", "Highest first-call resolution rate", "Created comprehensive FAQ database"] },
        { id: "5", name: "Emily W.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar5.png", email: "emily.w@cardealership.com", phone: "+1 (555) 555-6666", location: "Miami, FL", totalInteractions: 130, resolutionRate: 89, conversionRate: 13, averageSentiment: 0.76, specializations: ["Electric Vehicles", "New Car Models", "Customer Relationship Management"], topAchievements: ["Led successful launch of EV sales program", "Highest customer retention rate", "Innovative social media marketing campaign"] },
        { id: "6", name: "Michael J.", position: "Customer Service", avatar: "/dashboard/avatars/avatar6.png", email: "michael.j@cardealership.com", phone: "+1 (555) 666-7777", location: "Seattle, WA", totalInteractions: 170, resolutionRate: 94, conversionRate: 9, averageSentiment: 0.83, specializations: ["Conflict Resolution", "Customer Loyalty Programs", "Process Improvement"], topAchievements: ["Implemented new customer loyalty program", "Reduced customer wait times by 30%", "Highest positive feedback score"] },
        { id: "7", name: "Jessica T.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar7.png", email: "jessica.t@cardealership.com", phone: "+1 (555) 777-8888", location: "Boston, MA", totalInteractions: 135, resolutionRate: 91, conversionRate: 15, averageSentiment: 0.79, specializations: ["Sports Cars", "Custom Orders", "VIP Clients"], topAchievements: ["Top salesperson Q4 2023", "Highest average sale value", "Developed new VIP client program"] },
        { id: "8", name: "David L.", position: "Customer Service", avatar: "/dashboard/avatars/avatar8.png", email: "david.l@cardealership.com", phone: "+1 (555) 888-9999", location: "Denver, CO", totalInteractions: 155, resolutionRate: 92, conversionRate: 10, averageSentiment: 0.81, specializations: ["After-Sales Support", "Warranty Claims", "Customer Feedback Analysis"], topAchievements: ["Streamlined warranty claim process", "Implemented new customer feedback system", "Highest customer satisfaction improvement"] },
        { id: "9", name: "Sarah M.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar9.png", email: "sarah.m@cardealership.com", phone: "+1 (555) 999-0000", location: "San Francisco, CA", totalInteractions: 145, resolutionRate: 90, conversionRate: 14, averageSentiment: 0.77, specializations: ["Eco-Friendly Vehicles", "Fleet Sales", "Digital Marketing"], topAchievements: ["Led successful corporate fleet sales program", "Highest social media engagement rate", "Innovative virtual test drive program"] },
        { id: "10", name: "Daniel K.", position: "Customer Service", avatar: "/dashboard/avatars/avatar10.png", email: "daniel.k@cardealership.com", phone: "+1 (555) 000-1111", location: "Atlanta, GA", totalInteractions: 165, resolutionRate: 93, conversionRate: 11, averageSentiment: 0.84, specializations: ["Multi-lingual Support", "Customer Onboarding", "Service Scheduling"], topAchievements: ["Implemented new multi-lingual support system", "Highest customer retention rate", "Developed efficient service scheduling app"] },
        { id: "11", name: "Olivia G.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar11.png", email: "olivia.g@cardealership.com", phone: "+1 (555) 111-2222", location: "Dallas, TX", totalInteractions: 125, resolutionRate: 87, conversionRate: 13, averageSentiment: 0.74, specializations: ["Truck Sales", "Commercial Vehicles", "Trade-in Valuations"], topAchievements: ["Top commercial vehicle sales Q2 2023", "Highest trade-in conversion rate", "Developed new commercial client outreach program"] },
        { id: "12", name: "Ethan R.", position: "Customer Service", avatar: "/dashboard/avatars/avatar12.png", email: "ethan.r@cardealership.com", phone: "+1 (555) 222-3333", location: "Phoenix, AZ", totalInteractions: 175, resolutionRate: 94, conversionRate: 10, averageSentiment: 0.86, specializations: ["Technical Troubleshooting", "Customer Education", "Process Documentation"], topAchievements: ["Created comprehensive troubleshooting guide", "Highest customer education seminar attendance", "Implemented new knowledge base system"] },
        { id: "13", name: "Ava C.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar13.png", email: "ava.c@cardealership.com", phone: "+1 (555) 333-4444", location: "Philadelphia, PA", totalInteractions: 135, resolutionRate: 89, conversionRate: 14, averageSentiment: 0.78, specializations: ["Family Vehicles", "Safety Features", "Customer Relationship Management"], topAchievements: ["Top family vehicle sales Q3 2023", "Highest safety feature upsell rate", "Developed new family-focused marketing campaign"] },
        { id: "14", name: "Liam H.", position: "Customer Service", avatar: "/dashboard/avatars/avatar14.png", email: "liam.h@cardealership.com", phone: "+1 (555) 444-5555", location: "San Diego, CA", totalInteractions: 160, resolutionRate: 92, conversionRate: 11, averageSentiment: 0.83, specializations: ["Social Media Support", "Customer Feedback Analysis", "Chatbot Management"], topAchievements: ["Implemented new social media support strategy", "Highest chatbot resolution rate", "Developed innovative customer feedback visualization tool"] },
        { id: "15", name: "Mia W.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar15.png", email: "mia.w@cardealership.com", phone: "+1 (555) 555-6666", location: "Detroit, MI", totalInteractions: 140, resolutionRate: 90, conversionRate: 15, averageSentiment: 0.79, specializations: ["Classic Cars", "Restoration Services", "Collector Editions"], topAchievements: ["Top classic car sales Q1 2023", "Highest restoration service upsell rate", "Organized successful vintage car show event"] },
        { id: "16", name: "Noah J.", position: "Customer Service", avatar: "/dashboard/avatars/avatar16.png", email: "noah.j@cardealership.com", phone: "+1 (555) 666-7777", location: "Minneapolis, MN", totalInteractions: 170, resolutionRate: 93, conversionRate: 10, averageSentiment: 0.85, specializations: ["Customer Retention", "Loyalty Programs", "Feedback Implementation"], topAchievements: ["Highest customer retention improvement", "Successful launch of new loyalty program", "Implemented customer feedback-driven process improvements"] },
        { id: "17", name: "Emma T.", position: "Sales Representative", avatar: "/dashboard/avatars/avatar17.png", email: "emma.t@cardealership.com", phone: "+1 (555) 777-8888", location: "Portland, OR", totalInteractions: 130, resolutionRate: 88, conversionRate: 13, averageSentiment: 0.76, specializations: ["Green Vehicles", "Sustainability Features", "Eco-Friendly Initiatives"], topAchievements: ["Top green vehicle sales Q4 2023", "Highest sustainability feature adoption rate", "Led dealership's carbon neutrality initiative"] },
        { id: "18", name: "William L.", position: "Customer Service", avatar: "/dashboard/avatars/avatar18.png", email: "william.l@cardealership.com", phone: "+1 (555) 888-9999", location: "Las Vegas, NV", totalInteractions: 155, resolutionRate: 91, conversionRate: 11, averageSentiment: 0.82, specializations: ["VIP Customer Support", "Concierge Services", "Luxury Experience"], topAchievements: ["Highest VIP customer satisfaction score", "Implemented new concierge service program", "Developed luxury customer experience guidelines"] },
    ];

    const employee = employees.find(emp => emp.id === id);
    if (!employee) {
        throw new Error('Employee not found');
    }
    return employee;
}

export default async function TeamPage({ params }: { params: { id: string } }) {
    const employee = await getEmployeeData(params.id);

    return (
        <EmployeePerformanceComponent employee={employee} />
    );
}